// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"fiber/app/dao/internal"
)

// sysMediaDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type sysMediaDao struct {
	*internal.SysMediaDao
}

var (
	// SysMedia is globally public accessible object for table sys_media operations.
	SysMedia = &sysMediaDao{
		internal.SysMedia,
	}
)

// Fill with you ideas below.