// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"fiber/app/dao/internal"
)

// sysGradeDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type sysGradeDao struct {
	*internal.SysGradeDao
}

var (
	// SysGrade is globally public accessible object for table sys_grade operations.
	SysGrade = &sysGradeDao{
		internal.SysGrade,
	}
)

// Fill with you ideas below.