// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"fiber/app/dao/internal"
)

// sysVipDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type sysVipDao struct {
	*internal.SysVipDao
}

var (
	// SysVip is globally public accessible object for table sys_vip operations.
	SysVip = &sysVipDao{
		internal.SysVip,
	}
)

// Fill with you ideas below.