// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"fiber/app/dao/internal"
)

// sysArticleDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type sysArticleDao struct {
	*internal.SysArticleDao
}

var (
	// SysArticle is globally public accessible object for table sys_article operations.
	SysArticle = &sysArticleDao{
		internal.SysArticle,
	}
)

// Fill with you ideas below.