// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"fiber/app/dao/internal"
)

// sysAudioDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type sysAudioDao struct {
	*internal.SysAudioDao
}

var (
	// SysAudio is globally public accessible object for table sys_audio operations.
	SysAudio = &sysAudioDao{
		internal.SysAudio,
	}
)

// Fill with you ideas below.