// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"fiber/app/dao/internal"
)

// sysResourceDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type sysResourceDao struct {
	*internal.SysResourceDao
}

var (
	// SysResource is globally public accessible object for table sys_resource operations.
	SysResource = &sysResourceDao{
		internal.SysResource,
	}
)

// Fill with you ideas below.