// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"fiber/app/dao/internal"
)

// sysUserLikeDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type sysUserLikeDao struct {
	*internal.SysUserLikeDao
}

var (
	// SysUserLike is globally public accessible object for table sys_user_like operations.
	SysUserLike = &sysUserLikeDao{
		internal.SysUserLike,
	}
)

// Fill with you ideas below.