// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"fiber/app/dao/internal"
)

// sysUserFollowDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type sysUserFollowDao struct {
	*internal.SysUserFollowDao
}

var (
	// SysUserFollow is globally public accessible object for table sys_user_follow operations.
	SysUserFollow = &sysUserFollowDao{
		internal.SysUserFollow,
	}
)

// Fill with you ideas below.