// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"fiber/app/dao/internal"
)

// sysCommentDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type sysCommentDao struct {
	*internal.SysCommentDao
}

var (
	// SysComment is globally public accessible object for table sys_comment operations.
	SysComment = &sysCommentDao{
		internal.SysComment,
	}
)

// Fill with you ideas below.