// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"fiber/app/dao/internal"
)

// sysMediaRelatedDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type sysMediaRelatedDao struct {
	*internal.SysMediaRelatedDao
}

var (
	// SysMediaRelated is globally public accessible object for table sys_media_related operations.
	SysMediaRelated = &sysMediaRelatedDao{
		internal.SysMediaRelated,
	}
)

// Fill with you ideas below.