// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"fiber/app/dao/internal"
)

// sysTagDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type sysTagDao struct {
	*internal.SysTagDao
}

var (
	// SysTag is globally public accessible object for table sys_tag operations.
	SysTag = &sysTagDao{
		internal.SysTag,
	}
)

// Fill with you ideas below.