// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"fiber/app/dao/internal"
)

// sysCategoryDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type sysCategoryDao struct {
	*internal.SysCategoryDao
}

var (
	// SysCategory is globally public accessible object for table sys_category operations.
	SysCategory = &sysCategoryDao{
		internal.SysCategory,
	}
)

// Fill with you ideas below.