// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"fiber/app/dao/internal"
)

// sysUserVipDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type sysUserVipDao struct {
	*internal.SysUserVipDao
}

var (
	// SysUserVip is globally public accessible object for table sys_user_vip operations.
	SysUserVip = &sysUserVipDao{
		internal.SysUserVip,
	}
)

// Fill with you ideas below.