// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"fiber/app/dao/internal"
)

// sysCashDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type sysCashDao struct {
	*internal.SysCashDao
}

var (
	// SysCash is globally public accessible object for table sys_cash operations.
	SysCash = &sysCashDao{
		internal.SysCash,
	}
)

// Fill with you ideas below.