// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"fiber/app/dao/internal"
)

// sysUserFavoriteDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type sysUserFavoriteDao struct {
	*internal.SysUserFavoriteDao
}

var (
	// SysUserFavorite is globally public accessible object for table sys_user_favorite operations.
	SysUserFavorite = &sysUserFavoriteDao{
		internal.SysUserFavorite,
	}
)

// Fill with you ideas below.