// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"fiber/app/dao/internal"
)

// sysSignDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type sysSignDao struct {
	*internal.SysSignDao
}

var (
	// SysSign is globally public accessible object for table sys_sign operations.
	SysSign = &sysSignDao{
		internal.SysSign,
	}
)

// Fill with you ideas below.