// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"fiber/app/dao/internal"
)

// sysAuthorityDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type sysAuthorityDao struct {
	*internal.SysAuthorityDao
}

var (
	// SysAuthority is globally public accessible object for table sys_authority operations.
	SysAuthority = &sysAuthorityDao{
		internal.SysAuthority,
	}
)

// Fill with you ideas below.