// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"fiber/app/dao/internal"
)

// sysRechargeDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type sysRechargeDao struct {
	*internal.SysRechargeDao
}

var (
	// SysRecharge is globally public accessible object for table sys_recharge operations.
	SysRecharge = &sysRechargeDao{
		internal.SysRecharge,
	}
)

// Fill with you ideas below.