// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"fiber/app/dao/internal"
)

// sysEduDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type sysEduDao struct {
	*internal.SysEduDao
}

var (
	// SysEdu is globally public accessible object for table sys_edu operations.
	SysEdu = &sysEduDao{
		internal.SysEdu,
	}
)

// Fill with you ideas below.