// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"fiber/app/dao/internal"
)

// sysRoleAuthorityDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type sysRoleAuthorityDao struct {
	*internal.SysRoleAuthorityDao
}

var (
	// SysRoleAuthority is globally public accessible object for table sys_role_authority operations.
	SysRoleAuthority = &sysRoleAuthorityDao{
		internal.SysRoleAuthority,
	}
)

// Fill with you ideas below.