// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"fiber/app/dao/internal"
)

// sysVideoDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type sysVideoDao struct {
	*internal.SysVideoDao
}

var (
	// SysVideo is globally public accessible object for table sys_video operations.
	SysVideo = &sysVideoDao{
		internal.SysVideo,
	}
)

// Fill with you ideas below.