// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"fiber/app/dao/internal"
)

// sysMangerRoleDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type sysMangerRoleDao struct {
	*internal.SysMangerRoleDao
}

var (
	// SysMangerRole is globally public accessible object for table sys_manger_role operations.
	SysMangerRole = &sysMangerRoleDao{
		internal.SysMangerRole,
	}
)

// Fill with you ideas below.