// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"fiber/app/dao/internal"
)

// sysCardDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type sysCardDao struct {
	*internal.SysCardDao
}

var (
	// SysCard is globally public accessible object for table sys_card operations.
	SysCard = &sysCardDao{
		internal.SysCard,
	}
)

// Fill with you ideas below.