// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"fiber/app/model/internal"
)

// SysVip is the golang structure for table sys_vip.
type SysVip internal.SysVip

// Fill with you ideas below.