// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"fiber/app/model/internal"
)

// SysGroup is the golang structure for table sys_group.
type SysGroup internal.SysGroup

// Fill with you ideas below.