// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"fiber/app/model/internal"
)

// SysResource is the golang structure for table sys_resource.
type SysResource internal.SysResource

// Fill with you ideas below.