// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"fiber/app/model/internal"
)

// SysAuthority is the golang structure for table sys_authority.
type SysAuthority internal.SysAuthority

// Fill with you ideas below.