// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"fiber/app/model/internal"
)

// SysUserFollow is the golang structure for table sys_user_follow.
type SysUserFollow internal.SysUserFollow

// Fill with you ideas below.