// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"fiber/app/model/internal"
)

// SysCategory is the golang structure for table sys_category.
type SysCategory internal.SysCategory

// Fill with you ideas below.