// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"fiber/app/model/internal"
)

// SysAnswer is the golang structure for table sys_answer.
type SysAnswer internal.SysAnswer

// Fill with you ideas below.