// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"fiber/app/model/internal"
)

// SysUserJoinEdu is the golang structure for table sys_user_join_edu.
type SysUserJoinEdu internal.SysUserJoinEdu

// Fill with you ideas below.