// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"fiber/app/model/internal"
)

// SysUserVip is the golang structure for table sys_user_vip.
type SysUserVip internal.SysUserVip

// Fill with you ideas below.