// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"fiber/app/model/internal"
)

// SysRecharge is the golang structure for table sys_recharge.
type SysRecharge internal.SysRecharge

// Fill with you ideas below.