// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"fiber/app/model/internal"
)

// SysMedia is the golang structure for table sys_media.
type SysMedia internal.SysMedia

// Fill with you ideas below.