// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"fiber/app/model/internal"
)

// SysMediaRelated is the golang structure for table sys_media_related.
type SysMediaRelated internal.SysMediaRelated

// Fill with you ideas below.