// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"fiber/app/model/internal"
)

// SysVerify is the golang structure for table sys_verify.
type SysVerify internal.SysVerify

// Fill with you ideas below.