// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"fiber/app/model/internal"
)

// SysUser is the golang structure for table sys_user.
type SysUser internal.SysUser

// Fill with you ideas below.