// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"fiber/app/model/internal"
)

// SysAudio is the golang structure for table sys_audio.
type SysAudio internal.SysAudio

// Fill with you ideas below.