// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"fiber/app/model/internal"
)

// SysMangerRole is the golang structure for table sys_manger_role.
type SysMangerRole internal.SysMangerRole

// Fill with you ideas below.