// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"fiber/app/model/internal"
)

// SysTagRelated is the golang structure for table sys_tag_related.
type SysTagRelated internal.SysTagRelated

// Fill with you ideas below.