// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"fiber/app/model/internal"
)

// SysOrder is the golang structure for table sys_order.
type SysOrder internal.SysOrder

// Fill with you ideas below.