// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"fiber/app/model/internal"
)

// SysRoleAuthority is the golang structure for table sys_role_authority.
type SysRoleAuthority internal.SysRoleAuthority

// Fill with you ideas below.