// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"fiber/app/model/internal"
)

// SysUserJoinGroup is the golang structure for table sys_user_join_group.
type SysUserJoinGroup internal.SysUserJoinGroup

// Fill with you ideas below.