// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"fiber/app/model/internal"
)

// SysGrade is the golang structure for table sys_grade.
type SysGrade internal.SysGrade

// Fill with you ideas below.