// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"fiber/app/model/internal"
)

// SysComment is the golang structure for table sys_comment.
type SysComment internal.SysComment

// Fill with you ideas below.