// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"fiber/app/model/internal"
)

// SysManger is the golang structure for table sys_manger.
type SysManger internal.SysManger

// Fill with you ideas below.