// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"fiber/app/model/internal"
)

// SysCarousel is the golang structure for table sys_carousel.
type SysCarousel internal.SysCarousel

// Fill with you ideas below.