// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"fiber/app/model/internal"
)

// SysReport is the golang structure for table sys_report.
type SysReport internal.SysReport

// Fill with you ideas below.