// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"fiber/app/model/internal"
)

// SysTopic is the golang structure for table sys_topic.
type SysTopic internal.SysTopic

// Fill with you ideas below.