// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"fiber/app/model/internal"
)

// SysEdu is the golang structure for table sys_edu.
type SysEdu internal.SysEdu

// Fill with you ideas below.