// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"fiber/app/model/internal"
)

// SysSign is the golang structure for table sys_sign.
type SysSign internal.SysSign

// Fill with you ideas below.