// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"fiber/app/model/internal"
)

// SysCash is the golang structure for table sys_cash.
type SysCash internal.SysCash

// Fill with you ideas below.