// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"fiber/app/model/internal"
)

// SysVideo is the golang structure for table sys_video.
type SysVideo internal.SysVideo

// Fill with you ideas below.