// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"fiber/app/model/internal"
)

// SysUserFavorite is the golang structure for table sys_user_favorite.
type SysUserFavorite internal.SysUserFavorite

// Fill with you ideas below.