// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"fiber/app/model/internal"
)

// SysArticle is the golang structure for table sys_article.
type SysArticle internal.SysArticle

// Fill with you ideas below.