// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"fiber/app/model/internal"
)

// SysUserLike is the golang structure for table sys_user_like.
type SysUserLike internal.SysUserLike

// Fill with you ideas below.