// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// SysResource is the golang structure for table sys_resource.
type SysResource struct {
    ResourceId  int64       `orm:"resource_id,primary" json:"resourceId"`  //                                                      
    UserId      int64       `orm:"user_id"             json:"userId"`      // 发布的用户                                           
    CateId      int64       `orm:"cate_id"             json:"cateId"`      // 分类id                                               
    Hots        int64       `orm:"hots"                json:"hots"`        //                                                      
    Favorites   int64       `orm:"favorites"           json:"favorites"`   //                                                      
    Likes       int64       `orm:"likes"               json:"likes"`       //                                                      
    Views       int64       `orm:"views"               json:"views"`       // 阅读量                                               
    Title       string      `orm:"title"               json:"title"`       // 标题                                                 
    Content     string      `orm:"content"             json:"content"`     // 内容                                                 
    Cover       string      `orm:"cover"               json:"cover"`       // 封面                                                 
    HasDown     int         `orm:"has_down"            json:"hasDown"`     // 是否有下载1没有，2有                                 
    DownMode    int         `orm:"down_mode"           json:"downMode"`    // 下载权限 0公开下载，1付费下载，2评论下载，3登录下载  
    Price       float64     `orm:"price"               json:"price"`       //                                                      
    DownUrl     string      `orm:"down_url"            json:"downUrl"`     // 网盘地址                                             
    Purpose     string      `orm:"purpose"             json:"purpose"`     // 用途                                                 
    Attribute   string      `orm:"attribute"           json:"attribute"`   // 属性                                                 
    Description string      `orm:"description"         json:"description"` // 描述                                                 
    Status      int         `orm:"status"              json:"status"`      // 状态：0全部,1待审核 ，2已发布 ，3拒绝，4草稿         
    CreateTime  *gtime.Time `orm:"create_time"         json:"createTime"`  // 创建时间                                             
    UpdateTime  *gtime.Time `orm:"update_time"         json:"updateTime"`  // 更新时间                                             
    DeleteTime  *gtime.Time `orm:"delete_time"         json:"deleteTime"`  //                                                      
    Remark      string      `orm:"remark"              json:"remark"`      // 备注                                                 
}