// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal



// SysVip is the golang structure for table sys_vip.
type SysVip struct {
    VipId    int     `orm:"vip_id,primary" json:"vipId"`    //             
    Title    string  `orm:"title"          json:"title"`    // 会员标题    
    Icon     string  `orm:"icon"           json:"icon"`     //             
    Day      int     `orm:"day"            json:"day"`      // 到期时间    
    Price    float64 `orm:"price"          json:"price"`    // 开通价格    
    Discount float64 `orm:"discount"       json:"discount"` // 折扣        
    Color    string  `orm:"color"          json:"color"`    // 自定义颜色  
}