// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// SysTag is the golang structure for table sys_tag.
type SysTag struct {
    TagId      int64       `orm:"tag_id,primary" json:"tagId"`      //                         
    Title      string      `orm:"title"          json:"title"`      // 标题                    
    Top        int         `orm:"top"            json:"top"`        // 是否推荐 1不推荐 2推荐  
    CreateTime *gtime.Time `orm:"create_time"    json:"createTime"` // 创建日期                
}