// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// SysConfig is the golang structure for table sys_config.
type SysConfig struct {
    ConfigId    int         `orm:"config_id,primary" json:"configId"`    // 参数主键  
    ConfigName  string      `orm:"config_name"       json:"configName"`  // 参数名称  
    ConfigKey   string      `orm:"config_key"        json:"configKey"`   // 参数键名  
    ConfigValue string      `orm:"config_value"      json:"configValue"` // 参数键值  
    CreateTime  *gtime.Time `orm:"create_time"       json:"createTime"`  // 创建时间  
    UpdateTime  *gtime.Time `orm:"update_time"       json:"updateTime"`  // 更新时间  
    Remark      string      `orm:"remark"            json:"remark"`      // 备注      
}