// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal



// SysUserFavorite is the golang structure for table sys_user_favorite.
type SysUserFavorite struct {
    UserId     int64  `orm:"user_id"     json:"userId"`     //   
    FavoriteId int64  `orm:"favorite_id" json:"favoriteId"` //   
    Module     string `orm:"module"      json:"module"`     //   
}