// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal



// SysMangerRole is the golang structure for table sys_manger_role.
type SysMangerRole struct {
    UserId int64 `orm:"user_id,primary" json:"userId"` //   
    RoleId int64 `orm:"role_id,primary" json:"roleId"` //   
}