// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// SysDictType is the golang structure for table sys_dict_type.
type SysDictType struct {
    DictId     int64       `orm:"dict_id,primary" json:"dictId"`     // 字典主键              
    Title      string      `orm:"title"           json:"title"`      // 字典名称              
    Type       string      `orm:"type,unique"     json:"type"`       // 字典类型              
    Status     int         `orm:"status"          json:"status"`     // 状态（0正常，2停用）  
    CreateBy   int64       `orm:"create_by"       json:"createBy"`   //                       
    CreateTime *gtime.Time `orm:"create_time"     json:"createTime"` // 创建时间              
    UpdateTime *gtime.Time `orm:"update_time"     json:"updateTime"` // 更新时间              
    Remark     string      `orm:"remark"          json:"remark"`     // 备注                  
}