// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// SysNotice is the golang structure for table sys_notice.
type SysNotice struct {
    NoticeId     int64       `orm:"notice_id,primary" json:"noticeId"`     // 公告ID                                                                                          
    FromUserId   int64       `orm:"from_user_id"      json:"fromUserId"`   //                                                                                                 
    Receiver     int64       `orm:"receiver"          json:"receiver"`     // 接收者                                                                                          
    DetailModule string      `orm:"detail_module"     json:"detailModule"` //                                                                                                 
    DetailId     int64       `orm:"detail_id"         json:"detailId"`     //                                                                                                 
    SystemType   int         `orm:"system_type"       json:"systemType"`   // 1用户注册，2内容删除，3打赏收入，4购买收入，报名收入                                            
    Type         int         `orm:"type"              json:"type"`         // 通知类型 1用户注册通知,2内容删除通知,3用户收入通知,4评论通知,5回答通知,6获赞通知,7收到关注通知  
    Content      string      `orm:"content"           json:"content"`      // 内容                                                                                            
    Status       int         `orm:"status"            json:"status"`       // 是否阅读1未阅读，2已阅读                                                                        
    CreateTime   *gtime.Time `orm:"create_time"       json:"createTime"`   // 创建时间                                                                                        
}