// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal



// SysUserFollow is the golang structure for table sys_user_follow.
type SysUserFollow struct {
    UserId   int64 `orm:"user_id"   json:"userId"`   //   
    FollowId int64 `orm:"follow_id" json:"followId"` //   
}