// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// SysAuthority is the golang structure for table sys_authority.
type SysAuthority struct {
    AuthorityId int64       `orm:"authority_id,primary" json:"authorityId"` // 菜单ID                         
    Title       string      `orm:"title"                json:"title"`       // 菜单名称                       
    ParentId    int64       `orm:"parent_id"            json:"parentId"`    // 父菜单ID                       
    Component   string      `orm:"component"            json:"component"`   // 组件地址                       
    OrderBy     int         `orm:"order_by"             json:"orderBy"`     //                                
    Redirect    string      `orm:"redirect"             json:"redirect"`    // 跳转                           
    Path        string      `orm:"path"                 json:"path"`        // 请求地址                       
    Perms       string      `orm:"perms"                json:"perms"`       // 权限标识                       
    Target      int         `orm:"target"               json:"target"`      // 打开方式（1页签 2新窗口）      
    Type        int         `orm:"type"                 json:"type"`        // 菜单类型（1目录 2菜单 3按钮）  
    Hidden      int         `orm:"hidden"               json:"hidden"`      // 菜单状态（2显示 1隐藏）        
    Icon        string      `orm:"icon"                 json:"icon"`        // 菜单图标                       
    CreateTime  *gtime.Time `orm:"create_time"          json:"createTime"`  // 创建时间                       
    UpdateTime  *gtime.Time `orm:"update_time"          json:"updateTime"`  // 更新时间                       
    Remark      string      `orm:"remark"               json:"remark"`      // 备注                           
}