// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// SysSign is the golang structure for table sys_sign.
type SysSign struct {
    SignId     int64       `orm:"sign_id,primary" json:"signId"`     //   
    UserId     int64       `orm:"user_id"         json:"userId"`     //   
    Integral   int64       `orm:"integral"        json:"integral"`   //   
    Count      int         `orm:"count"           json:"count"`      //   
    CreateTime *gtime.Time `orm:"create_time"     json:"createTime"` //   
}