// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal



// SysGrade is the golang structure for table sys_grade.
type SysGrade struct {
    GradeId     int    `orm:"grade_id,primary" json:"gradeId"`     //   
    Title       string `orm:"title"            json:"title"`       //   
    Icon        string `orm:"icon"             json:"icon"`        //   
    Integral    int    `orm:"integral"         json:"integral"`    //   
    CreateGroup int    `orm:"create_group"     json:"createGroup"` //   
    PostsModule string `orm:"posts_module"     json:"postsModule"` //   
    CommonAuth  string `orm:"common_auth"      json:"commonAuth"`  //   
}