// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// SysOrder is the golang structure for table sys_order.
type SysOrder struct {
    OrderId          int64       `orm:"order_id,primary"   json:"orderId"`          //                                                                                                                             
    OrderNum         string      `orm:"order_num"          json:"orderNum"`         // 订单编号                                                                                                                    
    UserId           int64       `orm:"user_id"            json:"userId"`           // 下单人id                                                                                                                    
    AuthorId         int64       `orm:"author_id"          json:"authorId"`         // 作者id                                                                                                                      
    PayMethod        int         `orm:"pay_method"         json:"payMethod"`        // 支付方式：1支付宝，2微信，3余额                                                                                             
    OrderMoney       float64     `orm:"order_money"        json:"orderMoney"`       // 订单金额                                                                                                                    
    DistrictMoney    float64     `orm:"district_money"     json:"districtMoney"`    // 优惠金额                                                                                                                    
    AuthorMoney      float64     `orm:"author_money"       json:"authorMoney"`      // 作者收益                                                                                                                    
    ServiceMoney     float64     `orm:"service_money"      json:"serviceMoney"`     // 服务费                                                                                                                      
    PaymentMoney     float64     `orm:"payment_money"      json:"paymentMoney"`     // 支付金额                                                                                                                    
    OrderPoint       uint64      `orm:"order_point"        json:"orderPoint"`       // 订单积分                                                                                                                    
    OrderType        int         `orm:"order_type"         json:"orderType"`        // 订单类型: 1 充值，2打赏充电，3内容购买，4查看话题隐藏内容  ,5加入付费圈子,6购买付费课程,7查看付费答案，8开通vip，9认证付费  
    OrderMode        int         `orm:"order_mode"         json:"orderMode"`        // 订单方式：1虚拟物品，2实体物品                                                                                              
    ShippingMoney    float64     `orm:"shipping_money"     json:"shippingMoney"`    // 运输费用                                                                                                                    
    ShippingAddress  string      `orm:"shipping_address"   json:"shippingAddress"`  // 收获地址                                                                                                                    
    ShippingCompName string      `orm:"shipping_comp_name" json:"shippingCompName"` // 快递公司                                                                                                                    
    ShippingPhone    string      `orm:"shipping_phone"     json:"shippingPhone"`    // 收货人联系方式                                                                                                              
    ShippingName     string      `orm:"shipping_name"      json:"shippingName"`     // 收货人姓名                                                                                                                  
    ShippingSn       string      `orm:"shipping_sn"        json:"shippingSn"`       // 快递单号                                                                                                                    
    ShippingTime     *gtime.Time `orm:"shipping_time"      json:"shippingTime"`     // 发货时间                                                                                                                    
    DetailId         int64       `orm:"detail_id"          json:"detailId"`         //                                                                                                                             
    DetailModule     string      `orm:"detail_module"      json:"detailModule"`     //                                                                                                                             
    Status           int         `orm:"status"             json:"status"`           // 订单状态 1未支付，2已支付                                                                                                   
    Invoice          string      `orm:"invoice"            json:"invoice"`          // 发票抬头                                                                                                                    
    PayTime          *gtime.Time `orm:"pay_time"           json:"payTime"`          // 支付时间                                                                                                                    
    ReceiveTime      *gtime.Time `orm:"receive_time"       json:"receiveTime"`      // 收货时间                                                                                                                    
    CreateTime       *gtime.Time `orm:"create_time"        json:"createTime"`       // 创建时间                                                                                                                    
    UpdateTime       *gtime.Time `orm:"update_time"        json:"updateTime"`       // 最后修改时间                                                                                                                
}