// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// SysCategory is the golang structure for table sys_category.
type SysCategory struct {
    CateId      int64       `orm:"cate_id,primary" json:"cateId"`      //                                  
    ParentId    int64       `orm:"parent_id"       json:"parentId"`    // 顶级分类                         
    Module      string      `orm:"module"          json:"module"`      // 所属模块                         
    Title       string      `orm:"title"           json:"title"`       // 分类名称                         
    Slug        string      `orm:"slug"            json:"slug"`        // 分类别名                         
    Cover       string      `orm:"cover"           json:"cover"`       // 分类背景图                       
    Sort        int         `orm:"sort"            json:"sort"`        // 分类排序                         
    Keywords    string      `orm:"keywords"        json:"keywords"`    // 分类关键字                       
    Description string      `orm:"description"     json:"description"` // 分类描述                         
    IsTop       int         `orm:"isTop"           json:"isTop"`       // 分类状态 1 不推荐 2推荐          
    CreateTime  *gtime.Time `orm:"create_time"     json:"createTime"`  // 创建日期                         
    UpdateTime  *gtime.Time `orm:"update_time"     json:"updateTime"`  // 更新日期                         
    DeleteTime  *gtime.Time `orm:"delete_time"     json:"deleteTime"`  // 删除标志（0代表存在 2代表删除）  
}