// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal



// SysUserLike is the golang structure for table sys_user_like.
type SysUserLike struct {
    UserId    int64  `orm:"user_id,primary"    json:"userId"`    //   
    RelatedId int64  `orm:"related_id,primary" json:"relatedId"` //   
    Module    string `orm:"module,primary"     json:"module"`    //   
}