// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// SysReport is the golang structure for table sys_report.
type SysReport struct {
    ReportId    int64       `orm:"report_id,primary" json:"reportId"`    //                                                      
    UserId      int64       `orm:"user_id"           json:"userId"`      //                                                      
    RelatedId   int64       `orm:"related_id"        json:"relatedId"`   //                                                      
    Module      string      `orm:"module"            json:"module"`      //                                                      
    Type        int         `orm:"type"              json:"type"`        // 举报类型 1广告垃圾，2违规内容，3恶意灌水，4重复发帖  
    Description string      `orm:"description"       json:"description"` // 描述                                                 
    Remark      string      `orm:"remark"            json:"remark"`      //                                                      
    Status      int         `orm:"status"            json:"status"`      // 状态，2 已处理，1 未处理                             
    CreateTime  *gtime.Time `orm:"create_time"       json:"createTime"`  //                                                      
    UpdateTime  *gtime.Time `orm:"update_time"       json:"updateTime"`  //                                                      
}