// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal



// SysUserJoinGroup is the golang structure for table sys_user_join_group.
type SysUserJoinGroup struct {
    GroupId int64 `orm:"group_id" json:"groupId"` //   
    UserId  int64 `orm:"user_id"  json:"userId"`  //   
}