// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal



// SysTagRelated is the golang structure for table sys_tag_related.
type SysTagRelated struct {
    TagId     int64  `orm:"tag_id"     json:"tagId"`     //         
    RelatedId int64  `orm:"related_id" json:"relatedId"` // 关系id  
    Module    string `orm:"module"     json:"module"`    // 模块    
}