// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// SysArticle is the golang structure for table sys_article.
type SysArticle struct {
    ArticleId   int64       `orm:"article_id,primary" json:"articleId"`   //                                               
    UserId      int64       `orm:"user_id"            json:"userId"`      // 发布的用户                                    
    CateId      int64       `orm:"cate_id"            json:"cateId"`      // 分类id                                        
    Hots        int64       `orm:"hots"               json:"hots"`        //                                               
    Favorites   int64       `orm:"favorites"          json:"favorites"`   //                                               
    Likes       int64       `orm:"likes"              json:"likes"`       //                                               
    Views       int64       `orm:"views"              json:"views"`       // 阅读量                                        
    Title       string      `orm:"title"              json:"title"`       // 标题                                          
    Description string      `orm:"description"        json:"description"` // 描述                                          
    Content     string      `orm:"content"            json:"content"`     // 内容                                          
    Cover       string      `orm:"cover"              json:"cover"`       // 封面                                          
    Status      int         `orm:"status"             json:"status"`      // 状态：0全部,1待审核 ，2已发布 ，3拒绝，4草稿  
    CreateTime  *gtime.Time `orm:"create_time"        json:"createTime"`  // 创建时间                                      
    UpdateTime  *gtime.Time `orm:"update_time"        json:"updateTime"`  // 更新时间                                      
    DeleteTime  *gtime.Time `orm:"delete_time"        json:"deleteTime"`  //                                               
    Remark      string      `orm:"remark"             json:"remark"`      // 备注                                          
}