// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// SysEdu is the golang structure for table sys_edu.
type SysEdu struct {
    EduId       int64       `orm:"edu_id,primary" json:"eduId"`       //                                               
    UserId      int64       `orm:"user_id"        json:"userId"`      //                                               
    CateId      int64       `orm:"cate_id"        json:"cateId"`      // 分类                                          
    Title       string      `orm:"title"          json:"title"`       // 标题                                          
    Cover       string      `orm:"cover"          json:"cover"`       // 封面                                          
    Content     string      `orm:"content"        json:"content"`     //                                               
    Description string      `orm:"description"    json:"description"` // 描述                                          
    Section     string      `orm:"section"        json:"section"`     // 视频地址                                      
    Max         int         `orm:"max"            json:"max"`         //                                               
    Favorites   int64       `orm:"favorites"      json:"favorites"`   //                                               
    Likes       int64       `orm:"likes"          json:"likes"`       //                                               
    Joins       int64       `orm:"joins"          json:"joins"`       //                                               
    Hots        int64       `orm:"hots"           json:"hots"`        //                                               
    Views       int64       `orm:"views"          json:"views"`       // 播放量                                        
    Type        int         `orm:"type"           json:"type"`        // 课程类型 1线下，2线上                         
    JoinMode    int         `orm:"join_mode"      json:"joinMode"`    // 查看权限 1公开下载，2付费下载                 
    Price       float64     `orm:"price"          json:"price"`       //                                               
    Status      int         `orm:"status"         json:"status"`      // 状态：0全部,1待审核 ，2已发布 ，3拒绝，4草稿  
    DeleteTime  *gtime.Time `orm:"delete_time"    json:"deleteTime"`  //                                               
    CreateTime  *gtime.Time `orm:"create_time"    json:"createTime"`  //                                               
    UpdateTime  *gtime.Time `orm:"update_time"    json:"updateTime"`  //                                               
    Remark      string      `orm:"remark"         json:"remark"`      //                                               
}