// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// SysTopic is the golang structure for table sys_topic.
type SysTopic struct {
    TopicId    int64       `orm:"topic_id,primary" json:"topicId"`    //                                               
    UserId     int64       `orm:"user_id"          json:"userId"`     // 发布用户                                      
    GroupId    int64       `orm:"group_id"         json:"groupId"`    //                                               
    RelatedId  int64       `orm:"related_id"       json:"relatedId"`  // 关联内容的id                                  
    Module     string      `orm:"module"           json:"module"`     // 所属模块                                      
    Type       int         `orm:"type"             json:"type"`       // 类型 1帖子，2问答                             
    Title      string      `orm:"title"            json:"title"`      // 话题                                          
    Files      string      `orm:"files"            json:"files"`      // 文件链接                                      
    Views      int64       `orm:"views"            json:"views"`      // 查看                                          
    Likes      int64       `orm:"likes"            json:"likes"`      //                                               
    Hots       int64       `orm:"hots"             json:"hots"`       //                                               
    IsTop      int         `orm:"is_top"           json:"isTop"`      // 是否置顶 1 不置顶 2置顶                       
    Price      float64     `orm:"price"            json:"price"`      //                                               
    Status     int         `orm:"status"           json:"status"`     // 状态：0全部,1待审核 ，2已发布 ，3拒绝，4草稿  
    CreateTime *gtime.Time `orm:"create_time"      json:"createTime"` //                                               
    UpdateTime *gtime.Time `orm:"update_time"      json:"updateTime"` //                                               
    DeleteTime *gtime.Time `orm:"delete_time"      json:"deleteTime"` //                                               
    Remark     string      `orm:"remark"           json:"remark"`     // 备注                                          
}