// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// SysUserJoinEdu is the golang structure for table sys_user_join_edu.
type SysUserJoinEdu struct {
    Mode       int         `orm:"mode"        json:"mode"`       // 联系方式1微信，2QQ，3手机  
    Number     string      `orm:"number"      json:"number"`     //                            
    EduId      int64       `orm:"edu_id"      json:"eduId"`      //                            
    UserId     int64       `orm:"user_id"     json:"userId"`     //                            
    Name       string      `orm:"name"        json:"name"`       //                            
    CreateTime *gtime.Time `orm:"create_time" json:"createTime"` //                            
}