// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// SysVerify is the golang structure for table sys_verify.
type SysVerify struct {
    VerifyId   int64       `orm:"verify_id,primary" json:"verifyId"`   //                              
    UserId     int64       `orm:"user_id"           json:"userId"`     // 用户id                       
    Name       string      `orm:"name"              json:"name"`       // 真实姓名                     
    Code       string      `orm:"code"              json:"code"`       // 身份证号码                   
    Encryption string      `orm:"encryption"        json:"encryption"` // 加密后的认证信息             
    Mode       int         `orm:"mode"              json:"mode"`       // 联系方式 1 qq, 2微信         
    Number     string      `orm:"number"            json:"number"`     // 联系号码                     
    CreateTime *gtime.Time `orm:"create_time"       json:"createTime"` // 认证时间                     
    UpdateTime *gtime.Time `orm:"update_time"       json:"updateTime"` // 更新时间                     
    Remark     string      `orm:"remark"            json:"remark"`     // 备注                         
    Status     int         `orm:"status"            json:"status"`     // 状态（1待审，2成功，3拒绝）  
}