// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// SysRecharge is the golang structure for table sys_recharge.
type SysRecharge struct {
    RechargeId int64       `orm:"recharge_id,primary" json:"rechargeId"` //                                             
    UserId     int64       `orm:"user_id"             json:"userId"`     //                                             
    Code       string      `orm:"code"                json:"code"`       //                                             
    Money      float64     `orm:"money"               json:"money"`      // 充值金额                                    
    Mode       int         `orm:"mode"                json:"mode"`       // 充值方式：1支付宝，2微信，3卡密，4人工转账  
    CardKey    string      `orm:"card_key"            json:"cardKey"`    //                                             
    Name       string      `orm:"name"                json:"name"`       // 转账人名称                                  
    Type       int         `orm:"type"                json:"type"`       // 转账类型：1支付宝，2微信                    
    Number     string      `orm:"number"              json:"number"`     // 转账单号                                    
    Status     int         `orm:"status"              json:"status"`     // 充值状态：1待审核，2已充值，3未充值         
    CreateTime *gtime.Time `orm:"create_time"         json:"createTime"` //                                             
    UpdateTime *gtime.Time `orm:"update_time"         json:"updateTime"` //                                             
    Remark     string      `orm:"remark"              json:"remark"`     // 备注                                        
}