// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// SysCash is the golang structure for table sys_cash.
type SysCash struct {
    CashId       int64       `orm:"cash_id,primary" json:"cashId"`       //                                       
    UserId       int64       `orm:"user_id"         json:"userId"`       //                                       
    Code         string      `orm:"code"            json:"code"`         // 提现单号                              
    CashMoney    float64     `orm:"cash_money"      json:"cashMoney"`    //                                       
    ServiceMoney float64     `orm:"service_money"   json:"serviceMoney"` // 服务费                                
    Money        float64     `orm:"money"           json:"money"`        // 实际金额                              
    Mode         int         `orm:"mode"            json:"mode"`         // 方式，1人工转账，2第三方到账          
    Number       string      `orm:"number"          json:"number"`       // 账号                                  
    ReceiptNum   string      `orm:"receipt_num"     json:"receiptNum"`   //                                       
    PayMethod    int         `orm:"pay_method"      json:"payMethod"`    // 支付方式（1支付宝，2微信）            
    Status       int         `orm:"status"          json:"status"`       // 状态 1待审核，2审核通过，3审核不通过  
    Remark       string      `orm:"remark"          json:"remark"`       // 备注                                  
    CreateTime   *gtime.Time `orm:"create_time"     json:"createTime"`   //                                       
    UpdateTime   *gtime.Time `orm:"update_time"     json:"updateTime"`   //                                       
}